from datetime import datetime, timezone
from io import BytesIO
from uuid import uuid4

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.units import inch
from reportlab.graphics import renderPDF
from reportlab.graphics.barcode.qr import QrCodeWidget
from reportlab.graphics.shapes import Drawing
from reportlab.pdfgen import canvas


def level_for_score(score):
    if score >= 80:
        return "Cyber Suraksha Champion"
    if score >= 60:
        return "Cyber Safety Star"
    return "Cyber Awareness Learner"


def generate_certificate(user, score):
    today = datetime.now(timezone.utc).date()
    cert_id = f"CSG-{today.strftime('%Y%m%d')}-{uuid4().hex[:8].upper()}"
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=landscape(A4))
    width, height = landscape(A4)
    pdf.setStrokeColor(colors.HexColor("#0f766e"))
    pdf.setLineWidth(6)
    pdf.rect(0.35 * inch, 0.35 * inch, width - 0.7 * inch, height - 0.7 * inch)
    pdf.setFillColor(colors.HexColor("#0f172a"))
    pdf.setFont("Helvetica-Bold", 30)
    pdf.drawCentredString(width / 2, height - 1.3 * inch, "Cyber Suraksha Gram")
    pdf.setFont("Helvetica", 16)
    pdf.drawCentredString(width / 2, height - 1.75 * inch, "Awareness Certificate")
    pdf.setFont("Helvetica", 13)
    pdf.drawCentredString(width / 2, height - 2.4 * inch, "This certificate is awarded to")
    pdf.setFont("Helvetica-Bold", 26)
    pdf.drawCentredString(width / 2, height - 3.0 * inch, user.full_name)
    pdf.setFont("Helvetica", 14)
    pdf.drawCentredString(width / 2, height - 3.55 * inch, f"Score: {score}/100 | Level: {level_for_score(score)}")
    pdf.drawCentredString(width / 2, height - 4.05 * inch, f"Village: {user.village}, {user.district}")
    pdf.drawCentredString(width / 2, height - 4.65 * inch, f"Date: {today.isoformat()} | Certificate ID: {cert_id}")
    qr = QrCodeWidget(f"Cyber Suraksha Gram certificate verification: {cert_id}")
    bounds = qr.getBounds()
    size = 1.2 * inch
    drawing = Drawing(size, size, transform=[size / (bounds[2] - bounds[0]), 0, 0, size / (bounds[3] - bounds[1]), 0, 0])
    drawing.add(qr)
    renderPDF.draw(drawing, pdf, width - 2.0 * inch, 0.8 * inch)
    pdf.setFont("Helvetica", 10)
    pdf.drawCentredString(width / 2, 0.75 * inch, "Generated by Cyber Suraksha Gram")
    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    return buffer, cert_id
