from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from uuid import uuid4

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.units import inch
from reportlab.graphics import renderPDF
from reportlab.graphics.barcode.qr import QrCodeWidget
from reportlab.graphics.shapes import Drawing
from reportlab.pdfgen import canvas

ASSET_DIR = Path(__file__).resolve().parents[1] / "static" / "images"


def level_for_score(score):
    if score >= 80:
        return "Cyber Suraksha Champion"
    if score >= 60:
        return "Cyber Safety Star"
    return "Cyber Awareness Learner"


def generate_certificate(user, score):
    today = datetime.now(timezone.utc).date()
    cert_id = f"CSG-{today.strftime('%Y%m%d')}-{uuid4().hex[:8].upper()}"
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=landscape(A4))
    width, height = landscape(A4)
    pdf.setFillColor(colors.HexColor("#f8fbff"))
    pdf.rect(0, 0, width, height, fill=1, stroke=0)
    pdf.setStrokeColor(colors.Color(0.2, 0.65, 0.95, alpha=0.12))
    pdf.setLineWidth(0.5)
    for x in range(0, int(width), 34):
        pdf.line(x, 0.35 * inch, x + 120, height - 0.35 * inch)
    watermark = ASSET_DIR / "logo-preview.webp"
    if watermark.exists():
        pdf.saveState()
        try:
            pdf.setFillAlpha(0.12)
            pdf.setStrokeAlpha(0.12)
        except AttributeError:
            pass
        pdf.drawImage(str(watermark), width / 2 - 1.65 * inch, height / 2 - 1.65 * inch, width=3.3 * inch, height=3.3 * inch, preserveAspectRatio=True, mask="auto")
        pdf.restoreState()
    pdf.setStrokeColor(colors.HexColor("#0f766e"))
    pdf.setLineWidth(6)
    pdf.rect(0.35 * inch, 0.35 * inch, width - 0.7 * inch, height - 0.7 * inch)
    logo = ASSET_DIR / "logo-preview.webp"
    if logo.exists():
        pdf.drawImage(str(logo), width / 2 - 0.72 * inch, height - 1.25 * inch, width=1.44 * inch, height=0.95 * inch, preserveAspectRatio=True, mask="auto")
    pdf.setFillColor(colors.HexColor("#0f172a"))
    pdf.setFont("Helvetica-Bold", 30)
    pdf.drawCentredString(width / 2, height - 1.65 * inch, "Cyber Suraksha Gram")
    pdf.setFont("Helvetica", 16)
    pdf.drawCentredString(width / 2, height - 2.05 * inch, "Awareness Certificate")
    pdf.setFont("Helvetica", 13)
    pdf.drawCentredString(width / 2, height - 2.65 * inch, "This certificate is awarded to")
    pdf.setFont("Helvetica-Bold", 26)
    pdf.drawCentredString(width / 2, height - 3.2 * inch, user.full_name)
    pdf.setFont("Helvetica", 14)
    pdf.drawCentredString(width / 2, height - 3.8 * inch, f"Score: {score}/100 | Rank: {level_for_score(score)}")
    pdf.drawCentredString(width / 2, height - 4.28 * inch, f"Village: {user.village}, {user.district}")
    pdf.drawCentredString(width / 2, height - 4.82 * inch, f"Issue Date: {today.isoformat()} | Certificate ID: {cert_id}")
    qr = QrCodeWidget(f"Cyber Suraksha Gram certificate verification: {cert_id}")
    bounds = qr.getBounds()
    size = 1.2 * inch
    drawing = Drawing(size, size, transform=[size / (bounds[2] - bounds[0]), 0, 0, size / (bounds[3] - bounds[1]), 0, 0])
    drawing.add(qr)
    renderPDF.draw(drawing, pdf, width - 2.0 * inch, 0.78 * inch)
    pdf.setFont("Helvetica", 10)
    pdf.drawCentredString(width / 2, 0.75 * inch, "Generated by Cyber Suraksha Gram")
    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    return buffer, cert_id
